name: blaze_engine
description: A simple downloader package for Dart.
version: 0.1.0
homepage: https://github.com/agnath18K/blaze_engine
repository: https://github.com/agnath18K/blaze_engine
issue_tracker: https://github.com/agnath18K/blaze_engine/issues

environment:
  sdk: ^3.5.3

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
