name: blaze_engine
description: A simple downloader package for Dart.
version: 0.1.0
homepage: https://github.com/agnath18K/blaze_engine
repository: https://github.com/agnath18K/blaze_engine
issue_tracker: https://github.com/agnath18K/blaze_engine/issues
environment:
  sdk: ^3.5.3

dependencies:
  http: ^1.2.2
  path_provider: ^2.1.4

  path: any
dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0